### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by jasonrdzhou** [lpflpf/rocketmq-client4cpp-crack#1]
您好，请问下您说的修复内存泄露的问题，主要在哪几个地方，能帮忙指点下吗

**Comment by lpflpf** [comment]
比如，通过Topic查询订阅的消息队列时，构造了topicRouteData之后并未显示的释放内存。这种情况下会引发内存泄漏。

具体修复的内容，你可以通过对比我的分支与https://github.com/NDPMediaCorp/RocketMQ-Client4CPP 这个分支代码。
